wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.12.0
    cli_version: 0.16.6
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1715969840.0
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 2
      - 17
      - 23
      - 37
      4: 3.12.0
      5: 0.16.6
      8:
      - 1
      - 3
      - 5
      10:
      - 3
      13: windows-amd64
attention:
  desc: null
  value: 'No'
batchsize:
  desc: null
  value: 64
bi_directional:
  desc: null
  value: 'Yes'
cell_type:
  desc: null
  value: LSTM
decoder_layers:
  desc: null
  value: 3
dropout:
  desc: null
  value: 0.3
embedding_size:
  desc: null
  value: 256
encoder_layers:
  desc: null
  value: 2
epochs:
  desc: null
  value: 1
hidden_size:
  desc: null
  value: 1024
