wandb_version: 1

attention:
  value: 'No'
batchsize:
  value: 64
bi_directional:
  value: 'Yes'
cell_type:
  value: LSTM
decoder_layers:
  value: 3
dropout:
  value: 0.3
embedding_size:
  value: 256
encoder_layers:
  value: 2
epochs:
  value: 1
hidden_size:
  value: 1024
